// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYW0glPIzkiRjbIzzm922Y5Ye2qlEqQSE',
    appId: '1:669387880968:web:96804e012cdc7ddf8b6fbd',
    messagingSenderId: '669387880968',
    projectId: 'chatdo-d1fa5',
    authDomain: 'chatdo-d1fa5.firebaseapp.com',
    databaseURL: 'https://chatdo-d1fa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatdo-d1fa5.appspot.com',
    measurementId: 'G-K0FMZPCEFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWA_QzD7ER5iPo_UA7c2lvXWsHd7u8tto',
    appId: '1:669387880968:android:b6d3c80b50e802608b6fbd',
    messagingSenderId: '669387880968',
    projectId: 'chatdo-d1fa5',
    databaseURL: 'https://chatdo-d1fa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatdo-d1fa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_j_n8j4BoSZbycVLwC4wPk5Zk65miFpo',
    appId: '1:669387880968:ios:8478ce31e8dfaa398b6fbd',
    messagingSenderId: '669387880968',
    projectId: 'chatdo-d1fa5',
    databaseURL: 'https://chatdo-d1fa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatdo-d1fa5.appspot.com',
    iosClientId: '669387880968-3qa4obos748057j90slhgqhl8e7i3ufp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
